[info]
title = "Yet Another Blog"
description = "something something"
theme = "dark"
tmpl_home = "default"
tmpl_posts = "default"
author = "me"
contact = "me@tfwno.gf"
footer = "Built with <a href=\"https://github.com/underr/yasbe\">YASBE</a>"
# Title mode: how to display title; available options:
# jaden_smith: Show Titles Like This
# first_only: capitalize the first word
# lowercase: like this
# original: display exactly like the original filename
title_mode = "first_only"
